server:
  port: 8081
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3390/security?serverTimezone=Asia/Seoul
    username: cos
    password: cos1234

#  mvc:
#    view:
#      prefix: /templates/
#      suffix: .mustache
#  ???? ????? pom.xml? mustache? ?????? ???????? ???? ????? ???.

  jpa:
    hibernate:
      ddl-auto: update #create update none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 721804392400-qivta0koeimmsme8l6550a73g2c01u26.apps.googleusercontent.com
            client-secret: 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
            scope:
             - email
             - profile

          facebook:
            client-id: 266494765750431
            client-secret: 4b4a2dd2967b5000c3235af9d6410750
            scope:
              - email
              - public_profile

          naver:
            client-id: UZOP6ds_aoQolaaJu4jS
            client-secret: ulSZw_kCxW
            scope:
              - name
              - email
#              - profile_image
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8081/login/oauth2/code/naver #naver는 구글과 페이스북처럼 provider가 아니기때문에 /naver로 적어줘야된다.


        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response #회원정보를 json으로 받는데 response라는 키값으로 네이버가 리턴해줌.






